// <auto-generated />
using MessagingService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MessagingService.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20171128130304_IntialCreate1")]
    partial class IntialCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MessagingService.Models.MessageItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("isDraft");

                    b.Property<string>("message");

                    b.Property<string>("recipient");

                    b.Property<string>("sender");

                    b.Property<string>("subject");

                    b.HasKey("id");

                    b.ToTable("MessageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
